### ISSUE TITLE
The Python service only return one char when call ml-server service

### ISSUE THREAD

**Issue by wumingpu** [Microsoft/ML-Server-Python-Samples#1]
# here is the code:
from azureml.deploy import DeployClient
from azureml.deploy.server import MLServer
import pandas as pd

HOST = 'http://MyML-ServerHost:12800'
context = ('admin', 'myPassword')
client = DeployClient(HOST, use=MLServer, auth=context)

def runHelloWorld(par1, par2):
   listPars = ["HelloWorld",par1,par2]
   resStr = ','.join(listPars)
   return resStr

opts = {
   'version': 'v1.0.0',
   'description': 'Service description.',
   'code_fn': runHelloWorld,
   'inputs': {"par1": str,"par2":str},
   'outputs': {"resStr": str},
   'alias': 'runHelloWorld'
}

service = client.redeploy_service('runHelloWorld',**opts)

res = service.runHelloWorld("abc", "def")
answer = res.output('resStr')
print(res)
print(answer)

# The real result is:
<ServiceResponse> 
   api: /api/runHelloWorld/v1.0.0 
   error: 
   console_output: 
   outputs: {'resStr': 'H'}
   raw_outputs: {'resStr': 'H'}
   artifacts: {}
H

# The expect result is:
HelloWorld,abc,def

# The Question:
where is wrong with my python code??? why only return one char with this service??? please help me to see it, Thank you.

**Comment by efratshabtai** [comment]
Hello @wumingpu ,
This is a known issue with our current version where a python service returning a string will only return the first character. All other output types work well. This issue will be fixed in the next Microsoft Machine Learning Server which is coming out soon. 
Thank you for reporting, we appreciate your feedback.

**Comment by ramnov** [comment]
Hi @wumingpu , 

Here is a workaround using pandas dataframe : 
```
from azureml.deploy import DeployClient
from azureml.deploy.server import MLServer

HOST = 'http://MyML-ServerHost:12800'
context = ('admin', 'myPassword')
client = DeployClient(HOST, use=MLServer, auth=context)

def runHelloWorld(par1, par2):
    import pandas as pd
    listPars = ["HelloWorld",par1,par2]
    resStr = ','.join(listPars)
    return pd.DataFrame({'resStr':[resStr]})

opts = {
'version': 'v1.0.0',
'description': 'Service description.',
'code_fn': runHelloWorld,
'inputs': {"par1": str,"par2":str},
'outputs': {"resStr": pd.DataFrame},
'alias': 'runHelloWorld'
}

service = client.redeploy_service('runHelloWorld',**opts)

res = service.runHelloWorld("abc", "def")
answer = res.output('resStr')
print(answer)
```

# OUTPUT 

HelloWorld,abc,def
