### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by sqlshep** [Microsoft/ML-Server-Python-Samples#3]
The most of the code links in the https://github.com/microsoft/ML-Server-Python-Samples readme.md are broken.

**Comment by jeroenterheerdt** [comment]
good catch - I don't know why that happened. I'll fix it.

**Comment by jeroenterheerdt** [comment]
Thanks!

**Comment by sqlshep** [comment]
these too

https://github.com/microsoft/ML-Server-Python-Samples/blob/master/microsoftml/README.md

**Comment by jeroenterheerdt** [comment]
Thanks.

**Comment by sqlshep** [comment]
Thank YOU!
